sudo: required
services:
  - docker

before_install:
  - docker build -t hamzaabamboo/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run hamzaabamboo/react-test npm test -- --coverage

after_success:
  - docker build -t hamzaabamboo/multi-client ./client
  - docker build -t hamzaabamboo/multi-server ./server
  - docker build -t hamzaabamboo/multi-worker ./worker
  - docker build -t hamzaabamboo/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push hamzaabamboo/multi-client
  - docker push hamzaabamboo/multi-server
  - docker push hamzaabamboo/multi-worker
  - docker push hamzaabamboo/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: docker-complex-udemy-thing
  env: DockerComplexUdemyThing-env
  bucket_name: elasticbeanstalk-us-east-2-072979993612
  bucket_path: docker-complex
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
